"""Resolution Ticket schema — the full structured output for CS/Ops staff.

A ResolutionTicket is built DETERMINISTICALLY from rule engine output + evidence.
It is NOT generated by the LLM. The LLM only provides the human-readable summary
fields (issue_summary, problem_explanation, customer_reply_draft).

Safety invariants:
  - recommended_actions come from the rule engine mapping, not LLM.
  - execution_mode is always "draft_only" for money/account actions.
  - mcp_tool references are static mappings, not LLM-generated.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from fintech_agent.schemas.claim_verification import ClaimVerificationSummary


class AmountVerification(BaseModel):
    """Amount verification — shows trusted vs customer-claimed amounts.

    SAFETY: Action amounts MUST come from trusted system data, NEVER from
    customer complaint text. This model makes the source explicit for staff.

    Priority for trusted_amount:
        1. wallet_ledger.debit_amount
        2. transaction.amount
        3. reconciliation.bank_amount
    """

    customer_claimed_amount: int | None = Field(
        default=None,
        description="Số tiền khách hàng khai trong khiếu nại (chỉ tham khảo)",
    )
    trusted_amount: int | None = Field(
        default=None,
        description="Số tiền hệ thống ghi nhận (nguồn chuẩn)",
    )
    trusted_amount_source: str | None = Field(
        default=None,
        description="Nguồn dữ liệu chuẩn, vd: 'wallet_ledger.debit_amount'",
    )
    action_amount: int | None = Field(
        default=None,
        description="Số tiền sẽ dùng trong action (= trusted_amount)",
    )
    action_amount_source: str | None = Field(
        default=None,
        description="Nguồn của action_amount",
    )
    has_amount_mismatch: bool = Field(
        default=False,
        description="True nếu customer_claimed_amount != trusted_amount",
    )
    mismatch_description: str = Field(
        default="",
        description="Mô tả chênh lệch cho nhân viên",
    )


class TicketAction(BaseModel):
    """Single recommended action within a resolution ticket.

    Each action maps to a known MCP tool (or None for manual actions).
    The LLM does NOT decide actions — the rule engine does.
    All fields are populated deterministically by the ticket builder.
    """

    action_id: str = Field(
        default="",
        description="Unique identifier for this action, e.g. case_id:action_type",
    )
    action_name: str = Field(
        description="Tên hành động dễ hiểu, ví dụ: 'Tạo yêu cầu hoàn tiền'",
    )
    action_type: str = Field(
        description="ActionType enum value, ví dụ: 'create_refund_request_draft'",
    )
    description: str = Field(
        default="",
        description="Mô tả chi tiết action này làm gì",
    )
    mcp_tool: str | None = Field(
        default=None,
        description="MCP tool name nếu có, ví dụ: 'create_refund_draft'",
    )
    mcp_input: dict[str, Any] = Field(
        default_factory=dict,
        description="Input params cho MCP tool, ví dụ: {transaction_id, reason}",
    )
    preconditions: list[str] = Field(
        default_factory=list,
        description="Điều kiện tiên quyết để thực hiện action",
    )
    evidence_dependencies: list[str] = Field(
        default_factory=list,
        description="Danh sách evidence keys cần thiết cho action",
    )
    requires_approval: bool = Field(
        default=False,
        description="Có cần phê duyệt trước khi thực hiện không",
    )
    approval_status: str = Field(
        default="not_required",
        description="'not_required' | 'pending' | 'approved' | 'rejected'",
    )
    execution_mode: str = Field(
        default="manual",
        description="'draft_only' | 'read_only' | 'manual'",
    )
    risk_level: str = Field(
        default="unknown",
        description="Risk level for this action: low, medium, high, critical",
    )
    reason: str = Field(
        default="",
        description="Lý do đề xuất action này (diagnosis)",
    )
    status: str = Field(
        default="manual_required",
        description="'draft' | 'draft_ready' | 'waiting_approval' | 'manual_required'",
    )
    expected_result: str = Field(
        default="",
        description="Kết quả mong đợi khi thực hiện action",
    )
    safety_notes: list[str] = Field(
        default_factory=list,
        description="Các lưu ý an toàn riêng cho action này",
    )
    staff_instruction: str = Field(
        default="",
        description="Hướng dẫn chi tiết cho nhân viên về action này",
    )


class ResolutionTicket(BaseModel):
    """Full resolution ticket for a complaint case.

    Built deterministically from state + rule engine + evidence.
    The LLM summary is embedded for human-readable fields only.
    """

    ticket_id: str = Field(
        description="ID của ticket (= case_id)",
    )
    ticket_type: str = Field(
        default="unknown",
        description="Loại workflow: train_ticket, utility_bill, wallet_topup, etc.",
    )
    issue_summary: str = Field(
        default="",
        description="Tóm tắt vấn đề (từ LLM hoặc fallback)",
    )
    problem_location: str = Field(
        default="unknown",
        description="Nơi phát sinh vấn đề (từ LLM hoặc evidence)",
    )
    problem_explanation: str = Field(
        default="",
        description="Giải thích chi tiết vấn đề",
    )
    evidence_checked: list[str] = Field(
        default_factory=list,
        description="Danh sách evidence đã kiểm tra",
    )
    missing_evidence: list[str] = Field(
        default_factory=list,
        description="Danh sách evidence còn thiếu",
    )
    resolution_status: str = Field(
        default="not_supported",
        description="'actionable' | 'manual_review_required' | 'not_supported'",
    )
    recommended_actions: list[TicketAction] = Field(
        default_factory=list,
        description="Danh sách actions đề xuất (từ rule engine)",
    )
    staff_instruction: str = Field(
        default="",
        description="Hướng dẫn cho nhân viên CS/Ops",
    )
    customer_reply_draft: str = Field(
        default="",
        description="Câu trả lời nháp cho khách hàng",
    )
    safety_notes: list[str] = Field(
        default_factory=list,
        description="Các lưu ý an toàn",
    )
    amount_verification: AmountVerification | None = Field(
        default=None,
        description=(
            "Metadata xác minh số tiền: so sánh khách khai vs hệ thống. "
            "action_amount luôn lấy từ hệ thống, không từ complaint."
        ),
    )
    claim_verification: ClaimVerificationSummary | None = Field(
        default=None,
        description=(
            "Kết quả kiểm tra thông tin khách cung cấp. "
            "Phân biệt customer_detail_mismatch vs system_evidence_conflict."
        ),
    )
