"""Response generation schema — structured output from LLM summarization.

The GeneratedResponse is produced by the LLM response generator after
evidence + rule decision are finalized. It is a READ-ONLY summary —
it MUST NOT alter recommended_action, risk_level, or approval_required.

Safety invariants:
  - LLM generates text/explanation only, never changes decisions.
  - customer_reply_draft must not leak internal rules, thresholds, or secrets.
  - If action is draft/pending approval, text must clearly say so.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ResponseDebug(BaseModel):
    """Debug/observability metadata for generated response."""

    generation_mode: Literal["llm", "fallback"] = "fallback"
    fallback_reason: str | None = None
    llm_error: str | None = None
    model_used: str | None = None


class GeneratedResponse(BaseModel):
    """Structured response generated by LLM for CS/Ops staff.

    All fields are human-readable text. The LLM fills these based on
    evidence + decision context, but cannot change the underlying decision.
    """

    case_summary: str = Field(
        description="Tóm tắt ngắn gọn khiếu nại của khách hàng",
    )
    problem_location: str = Field(
        description=(
            "Nơi nhiều khả năng phát sinh vấn đề, ví dụ: wallet_system, bank, "
            "provider, fraud_system, reconciliation, customer_input, unknown, other"
        ),
    )
    problem_explanation: str = Field(
        description="Giải thích bằng ngôn ngữ dễ hiểu vấn đề đang nằm ở đâu và vì sao",
    )
    evidence_checked: list[str] = Field(
        default_factory=list,
        description="Danh sách evidence agent đã kiểm tra",
    )
    evidence_supporting_problem_location: list[str] = Field(
        default_factory=list,
        description=(
            "Các data point cụ thể từ structured evidence hỗ trợ kết luận problem_location, "
            "ví dụ: 'transaction.status=completed', 'provider.confirmed=false'"
        ),
    )
    problem_location_confidence: str = Field(
        default="unknown",
        description=(
            "Mức tin cậy của problem_location: "
            "'high' (nhiều evidence đồng ý), "
            "'medium' (một số evidence hỗ trợ nhưng thiếu 1 nguồn), "
            "'low' (complaint gợi ý nhưng thiếu structured evidence), "
            "'unknown' (không có evidence đáng tin cậy)"
        ),
    )
    internal_summary: str = Field(
        description="Tóm tắt nội bộ cho nhân viên CS/Ops",
    )
    recommended_next_step: str = Field(
        description="Bước tiếp theo nhân viên nên làm dựa trên action đã được rule engine quyết định",
    )
    customer_reply_draft: str = Field(
        description="Câu trả lời nháp cho khách hàng, không tiết lộ thông tin nội bộ",
    )
    safety_notes: list[str] = Field(
        default_factory=list,
        description="Các lưu ý an toàn, đặc biệt nếu action chỉ là draft hoặc cần phê duyệt",
    )
    missing_data: list[str] = Field(
        default_factory=list,
        description="Dữ liệu còn thiếu để kết luận chính xác hơn",
    )
    debug: ResponseDebug = Field(
        default_factory=ResponseDebug,
        description="Debug/observability info — generation_mode, errors, model used",
    )

